export const PERSONA_COPY = {
  velvet_intellectual: {
    briefTitle: "Today's Selection",
    briefSubtitle: "Your considered choice for today.",
    briefEmpty: "Your selection is waiting.",
    briefDone: "A considered day. Well chosen.",
    briefCTA: "What does it remind you of?",
    discoverHeadline: "The Study",
    discoverSubtitle: "127,000 fragrances, filtered to what suits you.",
    collectionHeadline: "The Cabinet",
    collectionEmpty: "Your cabinet is forming. Begin with one bottle.",
    identityHeadline: "Your identity",
    identityTagline: "The pattern in what you reach for.",
    rareLabel: "Rare reserve",
  },
  solar_minimalist: {
    briefTitle: "Today's Call",
    briefSubtitle: "Two seconds. Done.",
    briefEmpty: "Add bottles to start.",
    briefDone: "Sorted.",
    briefCTA: "Log it.",
    discoverHeadline: "The Study",
    discoverSubtitle: "Clean, confident, always right for the moment.",
    collectionHeadline: "The Cabinet",
    collectionEmpty: "Clean slate. Start building.",
    identityHeadline: "Your profile",
    identityTagline: "Efficient. Specific. Always intentional.",
    rareLabel: "Clean find",
  },
  dark_alchemist: {
    briefTitle: "Tonight's Formula",
    briefSubtitle: "What you reach for when the night begins.",
    briefEmpty: "Your lab is empty. Begin the collection.",
    briefDone: "The night is handled.",
    briefCTA: "What is this one?",
    discoverHeadline: "The Study",
    discoverSubtitle: "What they're not wearing. What you are.",
    collectionHeadline: "The Cabinet",
    collectionEmpty: "Empty lab. Unacceptable.",
    identityHeadline: "Your identity",
    identityTagline: "Bold. Polarising by design.",
    rareLabel: "Underground",
  },
  ritual_keeper: {
    briefTitle: "Morning Intention",
    briefSubtitle: "Begin with intention. Begin with this.",
    briefEmpty: "Your ritual is waiting.",
    briefDone: "The ritual is complete. A good start.",
    briefCTA: "What did this moment hold?",
    discoverHeadline: "The Study",
    discoverSubtitle: "Fragrances that hold meaning.",
    collectionHeadline: "The Cabinet",
    collectionEmpty: "Your practice is forming. Every bottle matters.",
    identityHeadline: "Your practice",
    identityTagline: "Intentional. Grounded. Sacred.",
    rareLabel: "Ceremonial",
  },
  rebel_experimentalist: {
    briefTitle: "Today's Experiment",
    briefSubtitle: "The one you're testing today.",
    briefEmpty: "Nothing to experiment with yet. Unacceptable.",
    briefDone: "Experiment complete. Notes?",
    briefCTA: "What happened?",
    discoverHeadline: "The Study",
    discoverSubtitle: "127,000 fragrances. Most of them are wrong for you.",
    collectionHeadline: "The Cabinet",
    collectionEmpty: "Empty studio. Fix that.",
    identityHeadline: "Your identity",
    identityTagline: "Unconventional. Creative. Always pushing.",
    rareLabel: "Cult obscure",
  },
  comfort_seeker: {
    briefTitle: "Today's Comfort",
    briefSubtitle: "The one that wraps around you today.",
    briefEmpty: "Your comfort awaits. Start here.",
    briefDone: "A good day. A good choice.",
    briefCTA: "What did this remind you of?",
    discoverHeadline: "The Study",
    discoverSubtitle: "Warm. Enveloping. Made for how you feel.",
    collectionHeadline: "The Cabinet",
    collectionEmpty: "Your favourites shelf is empty. Let's fix that.",
    identityHeadline: "Your identity",
    identityTagline: "Nurturing. Comforting. Always present.",
    rareLabel: "Hidden gem",
  },
} as const

export type PersonaCopyKey = keyof typeof PERSONA_COPY
export type PersonaCopy = typeof PERSONA_COPY[PersonaCopyKey]

export function getPersonaCopy(personaId: string | null): PersonaCopy {
  if (personaId && personaId in PERSONA_COPY) return PERSONA_COPY[personaId as PersonaCopyKey]
  return PERSONA_COPY.solar_minimalist
}
