#!/usr/bin/env -S npx tsx
// Export fragrance_facts / layering_patterns into NotebookLM-ready docs.
// Usage:
//   npx tsx scripts/export_knowledge.ts --target=wardrobe   (MASTER_WARDROBE.md + WARDROBE_INDEX.json)
//   npx tsx scripts/export_knowledge.ts --target=layering   (LAYERING_PATTERNS.md + WARDROBE_INDEX.json)
//   npx tsx scripts/export_knowledge.ts                     (both, default)
//
// Output lands in data/fragrance/canonical/ — the same folder the ingest
// pipeline drains processed source files into, so the whole knowledge base
// (sources + generated docs) is one NotebookLM notebook.
//
// Requires: NEXT_PUBLIC_SUPABASE_URL, SUPABASE_SERVICE_KEY in .env.local.
//
// Note: this does NOT touch the existing hand-curated docs/MASTER_WARDROBE.md
// — that file predates this pipeline. Output here is a separate,
// script-generated artifact so nothing curated gets silently overwritten.

import { createClient } from '@supabase/supabase-js'
import dotenv from 'dotenv'
import { writeFileSync } from 'fs'
import { join } from 'path'

dotenv.config({ path: '.env.local' })

const target = (process.argv.find((a) => a.startsWith('--target='))?.split('=')[1] ?? 'all') as
  | 'wardrobe'
  | 'layering'
  | 'all'

for (const key of ['NEXT_PUBLIC_SUPABASE_URL', 'SUPABASE_SERVICE_KEY']) {
  if (!process.env[key]) {
    console.error(`Missing ${key} in .env.local`)
    process.exit(1)
  }
}

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_KEY!,
)

const OUT_DIR = join(process.cwd(), 'data/fragrance/canonical')
const ROLE_LABELS: Record<string, string> = {
  anchor: 'Anchor (base-heavy — foundation + longevity)',
  modulator: 'Modulator (heart-heavy — complexity + texture)',
  top: 'Top (volatile/fresh — opening + radiance)',
}

async function fetchFacts() {
  const { data, error } = await supabase
    .from('fragrance_facts')
    .select('*')
    .order('role', { ascending: true })
    .order('brand', { ascending: true })
  if (error) throw new Error(`fragrance_facts fetch failed: ${error.message}`)
  return data ?? []
}

async function fetchPatterns() {
  const { data, error } = await supabase
    .from('layering_patterns')
    .select('*')
    .order('pattern_name', { ascending: true })
  if (error) throw new Error(`layering_patterns fetch failed: ${error.message}`)
  return data ?? []
}

function renderWardrobe(facts: Array<Record<string, unknown>>): string {
  const lines = [
    '# nota. — Knowledge Engine: Fragrance Facts',
    '',
    '> Generated by `npm run export:wardrobe` from the `fragrance_facts` table.',
    '> Source pipeline: `scripts/ingest_fragrance_sources.ts` (see docs/KNOWLEDGE_ENGINE.md).',
    '',
    '## Olfactory Phase Model',
    '- **Anchor:** base-heavy scents (oud, amber, musk, leather) — foundation + longevity.',
    '- **Modulator:** heart-heavy scents (florals, spices, resins) — complexity + texture.',
    '- **Top:** volatile, fresh scents (citrus, aquatics, fruits) — opening blast + radiance.',
    '',
  ]

  for (const role of ['anchor', 'modulator', 'top', null] as const) {
    const group = facts.filter((f) => (f.role ?? null) === role)
    if (group.length === 0) continue
    lines.push(`## ${role ? ROLE_LABELS[role] : 'Unclassified'}`, '')
    for (const f of group) {
      lines.push(`### ${f.brand ? `${f.brand} — ` : ''}${f.name}`)
      lines.push(`- **Top notes:** ${(f.top_notes as string[])?.join(', ') || 'N/A'}`)
      lines.push(`- **Heart notes:** ${(f.heart_notes as string[])?.join(', ') || 'N/A'}`)
      lines.push(`- **Base notes:** ${(f.base_notes as string[])?.join(', ') || 'N/A'}`)
      lines.push(`- **Accord families:** ${(f.accord_families as string[])?.join(', ') || 'N/A'}`)
      lines.push(`- **Source:** ${f.source_file}`)
      lines.push('')
    }
  }

  return lines.join('\n')
}

function renderLayering(patterns: Array<Record<string, unknown>>): string {
  const lines = [
    '# nota. — Knowledge Engine: Layering Patterns',
    '',
    '> Generated by `npm run export:layering` from the `layering_patterns` table.',
    '> Source pipeline: `scripts/ingest_fragrance_sources.ts` (see docs/KNOWLEDGE_ENGINE.md).',
    '',
  ]

  for (const p of patterns) {
    lines.push(`## ${p.pattern_name}`)
    if (p.use_case) lines.push(`- **Use case:** ${p.use_case}`)
    const names = p.fragrance_names as string[]
    const roles = p.roles as string[] | undefined
    lines.push(
      `- **Fragrances:** ${names.map((n, i) => (roles?.[i] ? `${n} (${roles[i]})` : n)).join(' → ')}`,
    )
    if (p.rationale) lines.push(`- **Rationale:** ${p.rationale}`)
    lines.push(`- **Source:** ${p.source_file}`)
    lines.push('')
  }

  return lines.join('\n')
}

async function main() {
  const facts = target !== 'layering' ? await fetchFacts() : []
  const patterns = target !== 'wardrobe' ? await fetchPatterns() : []

  if (target !== 'layering') {
    writeFileSync(join(OUT_DIR, 'MASTER_WARDROBE.md'), renderWardrobe(facts))
    console.log(`✓ MASTER_WARDROBE.md (${facts.length} facts)`)
  }
  if (target !== 'wardrobe') {
    writeFileSync(join(OUT_DIR, 'LAYERING_PATTERNS.md'), renderLayering(patterns))
    console.log(`✓ LAYERING_PATTERNS.md (${patterns.length} patterns)`)
  }

  writeFileSync(
    join(OUT_DIR, 'WARDROBE_INDEX.json'),
    JSON.stringify({ generated_at: new Date().toISOString(), facts, patterns }, null, 2),
  )
  console.log('✓ WARDROBE_INDEX.json')
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
