-- Add image_url column to fragrances table
-- This stores the public URL to the fragrance image generated by Gemini
-- Images are stored in the Supabase Storage bucket: fragrance-images

alter table fragrances add column if not exists image_url text;

-- Create index for queries filtering by image_url (to find fragrances without images)
create index if not exists fragrances_image_url_idx on fragrances(image_url);
