-- Epic 13: Insights Dashboard — Reaction tracking for traces and content
--
-- Original body here referenced public.profiles(anon_id), which doesn't
-- exist on production (profiles only has id — verified via Supabase MCP,
-- 2026-07-18) — this CREATE TABLE would abort a fresh replay immediately.
-- 20260717120000_align_trace_reactions_contract.sql already fully
-- supersedes this file: it creates public.trace_reactions from scratch
-- (trace_id/user_id/reaction, matching what's actually live) when the
-- table doesn't exist yet, and transforms the legacy anon_id/reaction_type
-- shape when it does. Left as a documented no-op rather than duplicating
-- that logic here.
SELECT 1;
